# Generated by Django 6.0.3 on 2026-04-08 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventpass'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventpass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='eventpass',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_adult', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price_child', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='AttendeeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child')], default='adult', max_length=10)),
                ('price_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('event_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.eventpass')),
                ('ticket_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.tickettype')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventpass',
            name='quantity',
        ),
    ]
