# Generated by Django 6.0.3 on 2026-04-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_eventpass_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeticket',
            name='attendee_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendeeticket',
            name='attendee_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='attendeeticket',
            name='attendee_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
