# Generated by Django 6.0.3 on 2026-04-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_attendeeticket_attendee_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='joining_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
